FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
RUN apk update && apk upgrade --no-cache && apk add --no-cache wget
COPY target/*.jar app.jar
RUN mkdir -p /uploads
EXPOSE 4000
ENTRYPOINT ["java", "-jar", "app.jar"]
